/// @description Insert description here
// You can write your code in this editor
var width=(display_get_gui_width());
var height=(display_get_gui_height());
draw_set_font(fnt_bold);
draw_set_halign(fa_left);
draw_set_color(c_white);
var spacing=16;
draw_sprite_pos(spr_charactersheetbkg,0,width/spacing,height/spacing,(width)-(width/spacing),height/spacing,(width)-(width/spacing),(height)-(height/spacing),width/spacing,(height)-(height/spacing),1);
var i=-3;
spacing=16;
var size=obj_aspectratio.aspect*2;
var sizex=(width/480)*1;
var sizey=height/480*1.25;
draw_text_transformed_color(width/16,height/4+(i*(height/spacing)),"Goal: Be the first player to bank 10 renown",sizex,sizey,0,c_silver,c_silver,c_silver,c_silver,1);	
i+=1;
draw_text_transformed_color(width/16,height/4+(i*(height/spacing)),"Renown: Acquire by completing Quests,",sizex,sizey,0,c_yellow,c_yellow,c_yellow,c_yellow,1);	
i+=1;
draw_text_transformed_color(width/16,height/4+(i*(height/spacing))," Events and duelling other players",sizex,sizey,0,c_yellow,c_yellow,c_yellow,c_yellow,1);	
i+=1;
draw_text_transformed_color(width/16,height/4+(i*(height/spacing)),"Quests: Scattered around the board- land",sizex,sizey,0,c_silver,c_silver,c_silver,c_silver,1);	
i+=1;
draw_text_transformed_color(width/16,height/4+(i*(height/spacing)),"on a quest and then try and beat its score",sizex,sizey,0,c_silver,c_silver,c_silver,c_silver,1);	
i+=1;
draw_text_transformed_color(width/16,height/4+(i*(height/spacing)),"Events: Players can go 1 space more than usual",sizex,sizey,0,c_yellow,c_yellow,c_yellow,c_yellow,1);	
i+=1;
draw_text_transformed_color(width/16,height/4+(i*(height/spacing)),"and take an event- it can be good or bad!",sizex,sizey,0,c_yellow,c_yellow,c_yellow,c_yellow,1);	
i+=1;
draw_text_transformed_color(width/16,height/4+(i*(height/spacing)),"Duelling: Bet your renown against another player!",sizex,sizey,0,c_silver,c_silver,c_silver,c_silver,1);	
i+=1;
draw_text_transformed_color(width/16,height/4+(i*(height/spacing))," (up to 5) Winner takes all! Defeated loses 1 hp ",sizex,sizey,0,c_silver,c_silver,c_silver,c_silver,1);	
i+=1;
draw_text_transformed_color(width/16,height/4+(i*(height/spacing)),"Town: Safe from duelling other players here,",sizex,sizey,0,c_yellow,c_yellow,c_yellow,c_yellow,1);	
i+=1;
draw_text_transformed_color(width/16,height/4+(i*(height/spacing)),"restore your health, able to buy items",sizex,sizey,0,c_yellow,c_yellow,c_yellow,c_yellow,1);	
i+=1;
draw_text_transformed_color(width/16,height/4+(i*(height/spacing)),"Castle: Where you go to bank your renown",sizex,sizey,0,c_silver,c_silver,c_silver,c_silver,1);	
i+=1;
draw_text_transformed_color(width/16,height/4+(i*(height/spacing)),"players always begin the game here",sizex,sizey,0,c_silver,c_silver,c_silver,c_silver,1);	
i+=1;
draw_set_color(c_white);
draw_set_halign(-1);
draw_set_valign(-1);
draw_set_font(-1);